name: keep_serv00

on:
  schedule:
    - cron: '0 */5 * * *'  # 每 5 小时执行一次
  workflow_dispatch:  
jobs:
  keep_serv00:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        server: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set server variables
        id: set_vars
        run: |
          if [ "${{ matrix.server }}" == "1" ]; then
            echo "SERVER_USERNAME=${{ secrets.SERVER1_USERNAME }}" >> $GITHUB_ENV
            echo "SERVER_HOSTNAME=${{ secrets.SERVER1_HOSTNAME }}" >> $GITHUB_ENV
            echo "SERVER_PASSWORD=${{ secrets.SERVER1_PASSWORD }}" >> $GITHUB_ENV
            echo "UDPPORT=39106" >> $GITHUB_ENV
          elif [ "${{ matrix.server }}" == "2" ]; then
            echo "SERVER_USERNAME=${{ secrets.SERVER2_USERNAME }}" >> $GITHUB_ENV
            echo "SERVER_HOSTNAME=${{ secrets.SERVER2_HOSTNAME }}" >> $GITHUB_ENV
            echo "SERVER_PASSWORD=${{ secrets.SERVER2_PASSWORD }}" >> $GITHUB_ENV
            echo "UDPPORT=58712" >> $GITHUB_ENV
          elif [ "${{ matrix.server }}" == "3" ]; then
            echo "SERVER_USERNAME=${{ secrets.SERVER3_USERNAME }}" >> $GITHUB_ENV
            echo "SERVER_HOSTNAME=${{ secrets.SERVER3_HOSTNAME }}" >> $GITHUB_ENV
            echo "SERVER_PASSWORD=${{ secrets.SERVER3_PASSWORD }}" >> $GITHUB_ENV
            echo "UDPPORT=62585" >> $GITHUB_ENV
          elif [ "${{ matrix.server }}" == "4" ]; then
            echo "SERVER_USERNAME=${{ secrets.SERVER4_USERNAME }}" >> $GITHUB_ENV
            echo "SERVER_HOSTNAME=${{ secrets.SERVER4_HOSTNAME }}" >> $GITHUB_ENV
            echo "SERVER_PASSWORD=${{ secrets.SERVER4_PASSWORD }}" >> $GITHUB_ENV
            echo "UDPPORT=62301" >> $GITHUB_ENV
          elif [ "${{ matrix.server }}" == "5" ]; then
            echo "SERVER_USERNAME=${{ secrets.SERVER5_USERNAME }}" >> $GITHUB_ENV
            echo "SERVER_HOSTNAME=${{ secrets.SERVER5_HOSTNAME }}" >> $GITHUB_ENV
            echo "SERVER_PASSWORD=${{ secrets.SERVER5_PASSWORD }}" >> $GITHUB_ENV
            echo "UDPPORT=23261" >> $GITHUB_ENV
          elif [ "${{ matrix.server }}" == "6" ]; then
            echo "SERVER_USERNAME=${{ secrets.SERVER6_USERNAME }}" >> $GITHUB_ENV
            echo "SERVER_HOSTNAME=${{ secrets.SERVER6_HOSTNAME }}" >> $GITHUB_ENV
            echo "SERVER_PASSWORD=${{ secrets.SERVER6_PASSWORD }}" >> $GITHUB_ENV
            echo "UDPPORT=29223" >> $GITHUB_ENV
          elif [ "${{ matrix.server }}" == "7" ]; then
            echo "SERVER_USERNAME=${{ secrets.SERVER7_USERNAME }}" >> $GITHUB_ENV
            echo "SERVER_HOSTNAME=${{ secrets.SERVER7_HOSTNAME }}" >> $GITHUB_ENV
            echo "SERVER_PASSWORD=${{ secrets.SERVER7_PASSWORD }}" >> $GITHUB_ENV
            echo "UDPPORT=33849" >> $GITHUB_ENV
          elif [ "${{ matrix.server }}" == "8" ]; then
            echo "SERVER_USERNAME=${{ secrets.SERVER8_USERNAME }}" >> $GITHUB_ENV
            echo "SERVER_HOSTNAME=${{ secrets.SERVER8_HOSTNAME }}" >> $GITHUB_ENV
            echo "SERVER_PASSWORD=${{ secrets.SERVER8_PASSWORD }}" >> $GITHUB_ENV
            echo "UDPPORT=58147" >> $GITHUB_ENV
          elif [ "${{ matrix.server }}" == "9" ]; then
            echo "SERVER_USERNAME=${{ secrets.SERVER9_USERNAME }}" >> $GITHUB_ENV
            echo "SERVER_HOSTNAME=${{ secrets.SERVER9_HOSTNAME }}" >> $GITHUB_ENV
            echo "SERVER_PASSWORD=${{ secrets.SERVER9_PASSWORD }}" >> $GITHUB_ENV
            echo "UDPPORT=31308" >> $GITHUB_ENV
          elif [ "${{ matrix.server }}" == "10" ]; then
            echo "SERVER_USERNAME=${{ secrets.SERVER10_USERNAME }}" >> $GITHUB_ENV
            echo "SERVER_HOSTNAME=${{ secrets.SERVER10_HOSTNAME }}" >> $GITHUB_ENV
            echo "SERVER_PASSWORD=${{ secrets.SERVER10_PASSWORD }}" >> $GITHUB_ENV
            echo "UDPPORT=33372" >> $GITHUB_ENV
          fi

      - name: Install sshpass
        run: sudo apt-get install -y sshpass || echo "sshpass already installed"

      - name: SSH into server and run script
        run: |
          sshpass -p "${{ env.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -T ${{ env.SERVER_USERNAME }}@${{ env.SERVER_HOSTNAME }} -o ConnectTimeout=10 2>/tmp/ssh_error.log || {
            echo -e "\033[31mSSH connection failed! Please check your SSH credentials or server status.\033[0m"
            echo -e "\033[31mError details:\033[0m"
            cat /tmp/ssh_error.log
            exit 1
           }
          
          sshpass -p "${{ env.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -T ${{ env.SERVER_USERNAME }}@${{ env.SERVER_HOSTNAME }} 2>/dev/null << EOF
            set -e 
            curl -Ls -H "Cache-Control: no-cache" "https://raw.githubusercontent.com/co2f2e/Serv00/main/bash/keep_serv00.sh" -o keep_serv00.sh || { echo 'Script download failed'; exit 1; }
            cat keep_serv00.sh
            bash keep_serv00.sh "${{ env.UDPPORT }}" || { echo 'Script execution failed'; exit 1; }
            if [ $? -eq 0 ]; then
              echo
              echo -e "\033[32mSuccess!!!\033[0m"
              echo
            else
              echo
              echo -e "\033[31mFailure!!!\033[0m"
              echo
              exit 1
            fi
          EOF
